services:
  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      - POSTGRES_USER=admin               
      - POSTGRES_PASSWORD=admin           
      - POSTGRES_DB=mydatabase            
    ports:
      - "5433:5432"                       
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
