server:
  port: 9000
management:
  server:
    port: 9001
    address: 127.0.0.1

spring:
  application:
    name: SpringBootStarter
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: alexjohnson
    password: password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
  # liquibase:
  #   change-log: classpath:db/changelog.sql

logging:
  level:
    org:
      springframework: INFO
